set(ESTER_KERNEL_SRC
    ${ESTER_DIR}/kernel/debug.c
    ${ESTER_DIR}/kernel/kernel.c
    ${ESTER_DIR}/kernel/string.c
    ${ESTER_DIR}/kernel/set_idt.c
    ${ESTER_DIR}/kernel/utils.c
    ${ESTER_DIR}/kernel/multiboot2_infostruct_parser.c
    ${ESTER_DIR}/kernel/ascii_utils.c
    ${ESTER_DIR}/kernel/printk.c
    ${ESTER_DIR}/kernel/mem.c
)